/*
Apodeixis backend

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UserKey type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserKey{}

// UserKey struct for UserKey
type UserKey struct {
	Id   string `json:"id"`
	Type string `json:"type"`
}

type _UserKey UserKey

// NewUserKey instantiates a new UserKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserKey(id string, type_ string) *UserKey {
	this := UserKey{}
	this.Id = id
	this.Type = type_
	return &this
}

// NewUserKeyWithDefaults instantiates a new UserKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserKeyWithDefaults() *UserKey {
	this := UserKey{}
	return &this
}

// GetId returns the Id field value
func (o *UserKey) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UserKey) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UserKey) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *UserKey) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UserKey) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UserKey) SetType(v string) {
	o.Type = v
}

func (o UserKey) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserKey) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *UserKey) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserKey := _UserKey{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserKey)

	if err != nil {
		return err
	}

	*o = UserKey(varUserKey)

	return err
}

type NullableUserKey struct {
	value *UserKey
	isSet bool
}

func (v NullableUserKey) Get() *UserKey {
	return v.value
}

func (v *NullableUserKey) Set(val *UserKey) {
	v.value = val
	v.isSet = true
}

func (v NullableUserKey) IsSet() bool {
	return v.isSet
}

func (v *NullableUserKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserKey(val *UserKey) *NullableUserKey {
	return &NullableUserKey{value: val, isSet: true}
}

func (v NullableUserKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
