/*
Apodeixis backend

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreatePost201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatePost201Response{}

// CreatePost201Response struct for CreatePost201Response
type CreatePost201Response struct {
	Data     Post                                 `json:"data"`
	Included []CreatePost201ResponseIncludedInner `json:"included"`
}

type _CreatePost201Response CreatePost201Response

// NewCreatePost201Response instantiates a new CreatePost201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePost201Response(data Post, included []CreatePost201ResponseIncludedInner) *CreatePost201Response {
	this := CreatePost201Response{}
	this.Data = data
	this.Included = included
	return &this
}

// NewCreatePost201ResponseWithDefaults instantiates a new CreatePost201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePost201ResponseWithDefaults() *CreatePost201Response {
	this := CreatePost201Response{}
	return &this
}

// GetData returns the Data field value
func (o *CreatePost201Response) GetData() Post {
	if o == nil {
		var ret Post
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreatePost201Response) GetDataOk() (*Post, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CreatePost201Response) SetData(v Post) {
	o.Data = v
}

// GetIncluded returns the Included field value
func (o *CreatePost201Response) GetIncluded() []CreatePost201ResponseIncludedInner {
	if o == nil {
		var ret []CreatePost201ResponseIncludedInner
		return ret
	}

	return o.Included
}

// GetIncludedOk returns a tuple with the Included field value
// and a boolean to check if the value has been set.
func (o *CreatePost201Response) GetIncludedOk() ([]CreatePost201ResponseIncludedInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Included, true
}

// SetIncluded sets field value
func (o *CreatePost201Response) SetIncluded(v []CreatePost201ResponseIncludedInner) {
	o.Included = v
}

func (o CreatePost201Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatePost201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["included"] = o.Included
	return toSerialize, nil
}

func (o *CreatePost201Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"included",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreatePost201Response := _CreatePost201Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreatePost201Response)

	if err != nil {
		return err
	}

	*o = CreatePost201Response(varCreatePost201Response)

	return err
}

type NullableCreatePost201Response struct {
	value *CreatePost201Response
	isSet bool
}

func (v NullableCreatePost201Response) Get() *CreatePost201Response {
	return v.value
}

func (v *NullableCreatePost201Response) Set(val *CreatePost201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePost201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePost201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePost201Response(val *CreatePost201Response) *NullableCreatePost201Response {
	return &NullableCreatePost201Response{value: val, isSet: true}
}

func (v NullableCreatePost201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePost201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
