/*
Apodeixis backend

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the OAuth2CallbackAllOfAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OAuth2CallbackAllOfAttributes{}

// OAuth2CallbackAllOfAttributes struct for OAuth2CallbackAllOfAttributes
type OAuth2CallbackAllOfAttributes struct {
	Code  string `json:"code"`
	State string `json:"state"`
}

type _OAuth2CallbackAllOfAttributes OAuth2CallbackAllOfAttributes

// NewOAuth2CallbackAllOfAttributes instantiates a new OAuth2CallbackAllOfAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOAuth2CallbackAllOfAttributes(code string, state string) *OAuth2CallbackAllOfAttributes {
	this := OAuth2CallbackAllOfAttributes{}
	this.Code = code
	this.State = state
	return &this
}

// NewOAuth2CallbackAllOfAttributesWithDefaults instantiates a new OAuth2CallbackAllOfAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOAuth2CallbackAllOfAttributesWithDefaults() *OAuth2CallbackAllOfAttributes {
	this := OAuth2CallbackAllOfAttributes{}
	return &this
}

// GetCode returns the Code field value
func (o *OAuth2CallbackAllOfAttributes) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *OAuth2CallbackAllOfAttributes) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *OAuth2CallbackAllOfAttributes) SetCode(v string) {
	o.Code = v
}

// GetState returns the State field value
func (o *OAuth2CallbackAllOfAttributes) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *OAuth2CallbackAllOfAttributes) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *OAuth2CallbackAllOfAttributes) SetState(v string) {
	o.State = v
}

func (o OAuth2CallbackAllOfAttributes) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OAuth2CallbackAllOfAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["state"] = o.State
	return toSerialize, nil
}

func (o *OAuth2CallbackAllOfAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
		"state",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOAuth2CallbackAllOfAttributes := _OAuth2CallbackAllOfAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOAuth2CallbackAllOfAttributes)

	if err != nil {
		return err
	}

	*o = OAuth2CallbackAllOfAttributes(varOAuth2CallbackAllOfAttributes)

	return err
}

type NullableOAuth2CallbackAllOfAttributes struct {
	value *OAuth2CallbackAllOfAttributes
	isSet bool
}

func (v NullableOAuth2CallbackAllOfAttributes) Get() *OAuth2CallbackAllOfAttributes {
	return v.value
}

func (v *NullableOAuth2CallbackAllOfAttributes) Set(val *OAuth2CallbackAllOfAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableOAuth2CallbackAllOfAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableOAuth2CallbackAllOfAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOAuth2CallbackAllOfAttributes(val *OAuth2CallbackAllOfAttributes) *NullableOAuth2CallbackAllOfAttributes {
	return &NullableOAuth2CallbackAllOfAttributes{value: val, isSet: true}
}

func (v NullableOAuth2CallbackAllOfAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOAuth2CallbackAllOfAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
