/*
Apodeixis backend

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Login200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Login200Response{}

// Login200Response User and if email is confirmed, AuthToken.
type Login200Response struct {
	Data     User                            `json:"data"`
	Included []Login200ResponseIncludedInner `json:"included,omitempty"`
}

type _Login200Response Login200Response

// NewLogin200Response instantiates a new Login200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLogin200Response(data User) *Login200Response {
	this := Login200Response{}
	this.Data = data
	return &this
}

// NewLogin200ResponseWithDefaults instantiates a new Login200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLogin200ResponseWithDefaults() *Login200Response {
	this := Login200Response{}
	return &this
}

// GetData returns the Data field value
func (o *Login200Response) GetData() User {
	if o == nil {
		var ret User
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *Login200Response) GetDataOk() (*User, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *Login200Response) SetData(v User) {
	o.Data = v
}

// GetIncluded returns the Included field value if set, zero value otherwise.
func (o *Login200Response) GetIncluded() []Login200ResponseIncludedInner {
	if o == nil || IsNil(o.Included) {
		var ret []Login200ResponseIncludedInner
		return ret
	}
	return o.Included
}

// GetIncludedOk returns a tuple with the Included field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Login200Response) GetIncludedOk() ([]Login200ResponseIncludedInner, bool) {
	if o == nil || IsNil(o.Included) {
		return nil, false
	}
	return o.Included, true
}

// HasIncluded returns a boolean if a field has been set.
func (o *Login200Response) HasIncluded() bool {
	if o != nil && !IsNil(o.Included) {
		return true
	}

	return false
}

// SetIncluded gets a reference to the given []Login200ResponseIncludedInner and assigns it to the Included field.
func (o *Login200Response) SetIncluded(v []Login200ResponseIncludedInner) {
	o.Included = v
}

func (o Login200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Login200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	if !IsNil(o.Included) {
		toSerialize["included"] = o.Included
	}
	return toSerialize, nil
}

func (o *Login200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLogin200Response := _Login200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLogin200Response)

	if err != nil {
		return err
	}

	*o = Login200Response(varLogin200Response)

	return err
}

type NullableLogin200Response struct {
	value *Login200Response
	isSet bool
}

func (v NullableLogin200Response) Get() *Login200Response {
	return v.value
}

func (v *NullableLogin200Response) Set(val *Login200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableLogin200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableLogin200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLogin200Response(val *Login200Response) *NullableLogin200Response {
	return &NullableLogin200Response{value: val, isSet: true}
}

func (v NullableLogin200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLogin200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
