/*
Apodeixis backend

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the EmailAllOfAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmailAllOfAttributes{}

// EmailAllOfAttributes struct for EmailAllOfAttributes
type EmailAllOfAttributes struct {
	Email string `json:"email"`
}

type _EmailAllOfAttributes EmailAllOfAttributes

// NewEmailAllOfAttributes instantiates a new EmailAllOfAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailAllOfAttributes(email string) *EmailAllOfAttributes {
	this := EmailAllOfAttributes{}
	this.Email = email
	return &this
}

// NewEmailAllOfAttributesWithDefaults instantiates a new EmailAllOfAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailAllOfAttributesWithDefaults() *EmailAllOfAttributes {
	this := EmailAllOfAttributes{}
	return &this
}

// GetEmail returns the Email field value
func (o *EmailAllOfAttributes) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *EmailAllOfAttributes) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *EmailAllOfAttributes) SetEmail(v string) {
	o.Email = v
}

func (o EmailAllOfAttributes) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmailAllOfAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	return toSerialize, nil
}

func (o *EmailAllOfAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmailAllOfAttributes := _EmailAllOfAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmailAllOfAttributes)

	if err != nil {
		return err
	}

	*o = EmailAllOfAttributes(varEmailAllOfAttributes)

	return err
}

type NullableEmailAllOfAttributes struct {
	value *EmailAllOfAttributes
	isSet bool
}

func (v NullableEmailAllOfAttributes) Get() *EmailAllOfAttributes {
	return v.value
}

func (v *NullableEmailAllOfAttributes) Set(val *EmailAllOfAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailAllOfAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailAllOfAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailAllOfAttributes(val *EmailAllOfAttributes) *NullableEmailAllOfAttributes {
	return &NullableEmailAllOfAttributes{value: val, isSet: true}
}

func (v NullableEmailAllOfAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailAllOfAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
