/*
Apodeixis backend

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the EmailToken type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmailToken{}

// EmailToken struct for EmailToken
type EmailToken struct {
	Type       string                    `json:"type"`
	Attributes EmailTokenAllOfAttributes `json:"attributes"`
}

type _EmailToken EmailToken

// NewEmailToken instantiates a new EmailToken object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailToken(type_ string, attributes EmailTokenAllOfAttributes) *EmailToken {
	this := EmailToken{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewEmailTokenWithDefaults instantiates a new EmailToken object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailTokenWithDefaults() *EmailToken {
	this := EmailToken{}
	return &this
}

// GetType returns the Type field value
func (o *EmailToken) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *EmailToken) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *EmailToken) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *EmailToken) GetAttributes() EmailTokenAllOfAttributes {
	if o == nil {
		var ret EmailTokenAllOfAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *EmailToken) GetAttributesOk() (*EmailTokenAllOfAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *EmailToken) SetAttributes(v EmailTokenAllOfAttributes) {
	o.Attributes = v
}

func (o EmailToken) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmailToken) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *EmailToken) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmailToken := _EmailToken{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmailToken)

	if err != nil {
		return err
	}

	*o = EmailToken(varEmailToken)

	return err
}

type NullableEmailToken struct {
	value *EmailToken
	isSet bool
}

func (v NullableEmailToken) Get() *EmailToken {
	return v.value
}

func (v *NullableEmailToken) Set(val *EmailToken) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailToken) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailToken) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailToken(val *EmailToken) *NullableEmailToken {
	return &NullableEmailToken{value: val, isSet: true}
}

func (v NullableEmailToken) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailToken) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
