/*
Apodeixis backend

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the VerifyEmailCallbackRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerifyEmailCallbackRequest{}

// VerifyEmailCallbackRequest struct for VerifyEmailCallbackRequest
type VerifyEmailCallbackRequest struct {
	Data EmailToken `json:"data"`
}

type _VerifyEmailCallbackRequest VerifyEmailCallbackRequest

// NewVerifyEmailCallbackRequest instantiates a new VerifyEmailCallbackRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerifyEmailCallbackRequest(data EmailToken) *VerifyEmailCallbackRequest {
	this := VerifyEmailCallbackRequest{}
	this.Data = data
	return &this
}

// NewVerifyEmailCallbackRequestWithDefaults instantiates a new VerifyEmailCallbackRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerifyEmailCallbackRequestWithDefaults() *VerifyEmailCallbackRequest {
	this := VerifyEmailCallbackRequest{}
	return &this
}

// GetData returns the Data field value
func (o *VerifyEmailCallbackRequest) GetData() EmailToken {
	if o == nil {
		var ret EmailToken
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *VerifyEmailCallbackRequest) GetDataOk() (*EmailToken, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *VerifyEmailCallbackRequest) SetData(v EmailToken) {
	o.Data = v
}

func (o VerifyEmailCallbackRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerifyEmailCallbackRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *VerifyEmailCallbackRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVerifyEmailCallbackRequest := _VerifyEmailCallbackRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVerifyEmailCallbackRequest)

	if err != nil {
		return err
	}

	*o = VerifyEmailCallbackRequest(varVerifyEmailCallbackRequest)

	return err
}

type NullableVerifyEmailCallbackRequest struct {
	value *VerifyEmailCallbackRequest
	isSet bool
}

func (v NullableVerifyEmailCallbackRequest) Get() *VerifyEmailCallbackRequest {
	return v.value
}

func (v *NullableVerifyEmailCallbackRequest) Set(val *VerifyEmailCallbackRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVerifyEmailCallbackRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVerifyEmailCallbackRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerifyEmailCallbackRequest(val *VerifyEmailCallbackRequest) *NullableVerifyEmailCallbackRequest {
	return &NullableVerifyEmailCallbackRequest{value: val, isSet: true}
}

func (v NullableVerifyEmailCallbackRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerifyEmailCallbackRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
