/*
Apodeixis backend

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"fmt"
)

// Login200ResponseIncludedInner struct for Login200ResponseIncludedInner
type Login200ResponseIncludedInner struct {
	AuthToken *AuthToken
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *Login200ResponseIncludedInner) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into AuthToken
	err = json.Unmarshal(data, &dst.AuthToken)
	if err == nil {
		jsonAuthToken, _ := json.Marshal(dst.AuthToken)
		if string(jsonAuthToken) == "{}" { // empty struct
			dst.AuthToken = nil
		} else {
			return nil // data stored in dst.AuthToken, return on the first match
		}
	} else {
		dst.AuthToken = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(Login200ResponseIncludedInner)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *Login200ResponseIncludedInner) MarshalJSON() ([]byte, error) {
	if src.AuthToken != nil {
		return json.Marshal(&src.AuthToken)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableLogin200ResponseIncludedInner struct {
	value *Login200ResponseIncludedInner
	isSet bool
}

func (v NullableLogin200ResponseIncludedInner) Get() *Login200ResponseIncludedInner {
	return v.value
}

func (v *NullableLogin200ResponseIncludedInner) Set(val *Login200ResponseIncludedInner) {
	v.value = val
	v.isSet = true
}

func (v NullableLogin200ResponseIncludedInner) IsSet() bool {
	return v.isSet
}

func (v *NullableLogin200ResponseIncludedInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLogin200ResponseIncludedInner(val *Login200ResponseIncludedInner) *NullableLogin200ResponseIncludedInner {
	return &NullableLogin200ResponseIncludedInner{value: val, isSet: true}
}

func (v NullableLogin200ResponseIncludedInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLogin200ResponseIncludedInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
