/*
Apodeixis backend

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetPostsAmount200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetPostsAmount200Response{}

// GetPostsAmount200Response struct for GetPostsAmount200Response
type GetPostsAmount200Response struct {
	Data PostsAmount `json:"data"`
}

type _GetPostsAmount200Response GetPostsAmount200Response

// NewGetPostsAmount200Response instantiates a new GetPostsAmount200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPostsAmount200Response(data PostsAmount) *GetPostsAmount200Response {
	this := GetPostsAmount200Response{}
	this.Data = data
	return &this
}

// NewGetPostsAmount200ResponseWithDefaults instantiates a new GetPostsAmount200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPostsAmount200ResponseWithDefaults() *GetPostsAmount200Response {
	this := GetPostsAmount200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetPostsAmount200Response) GetData() PostsAmount {
	if o == nil {
		var ret PostsAmount
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetPostsAmount200Response) GetDataOk() (*PostsAmount, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetPostsAmount200Response) SetData(v PostsAmount) {
	o.Data = v
}

func (o GetPostsAmount200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetPostsAmount200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *GetPostsAmount200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetPostsAmount200Response := _GetPostsAmount200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetPostsAmount200Response)

	if err != nil {
		return err
	}

	*o = GetPostsAmount200Response(varGetPostsAmount200Response)

	return err
}

type NullableGetPostsAmount200Response struct {
	value *GetPostsAmount200Response
	isSet bool
}

func (v NullableGetPostsAmount200Response) Get() *GetPostsAmount200Response {
	return v.value
}

func (v *NullableGetPostsAmount200Response) Set(val *GetPostsAmount200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPostsAmount200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPostsAmount200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPostsAmount200Response(val *GetPostsAmount200Response) *NullableGetPostsAmount200Response {
	return &NullableGetPostsAmount200Response{value: val, isSet: true}
}

func (v NullableGetPostsAmount200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPostsAmount200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
