/*
Apodeixis backend

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the EmailTokenAllOfAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmailTokenAllOfAttributes{}

// EmailTokenAllOfAttributes struct for EmailTokenAllOfAttributes
type EmailTokenAllOfAttributes struct {
	Token string `json:"token"`
}

type _EmailTokenAllOfAttributes EmailTokenAllOfAttributes

// NewEmailTokenAllOfAttributes instantiates a new EmailTokenAllOfAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailTokenAllOfAttributes(token string) *EmailTokenAllOfAttributes {
	this := EmailTokenAllOfAttributes{}
	this.Token = token
	return &this
}

// NewEmailTokenAllOfAttributesWithDefaults instantiates a new EmailTokenAllOfAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailTokenAllOfAttributesWithDefaults() *EmailTokenAllOfAttributes {
	this := EmailTokenAllOfAttributes{}
	return &this
}

// GetToken returns the Token field value
func (o *EmailTokenAllOfAttributes) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *EmailTokenAllOfAttributes) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *EmailTokenAllOfAttributes) SetToken(v string) {
	o.Token = v
}

func (o EmailTokenAllOfAttributes) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmailTokenAllOfAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["token"] = o.Token
	return toSerialize, nil
}

func (o *EmailTokenAllOfAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmailTokenAllOfAttributes := _EmailTokenAllOfAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmailTokenAllOfAttributes)

	if err != nil {
		return err
	}

	*o = EmailTokenAllOfAttributes(varEmailTokenAllOfAttributes)

	return err
}

type NullableEmailTokenAllOfAttributes struct {
	value *EmailTokenAllOfAttributes
	isSet bool
}

func (v NullableEmailTokenAllOfAttributes) Get() *EmailTokenAllOfAttributes {
	return v.value
}

func (v *NullableEmailTokenAllOfAttributes) Set(val *EmailTokenAllOfAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailTokenAllOfAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailTokenAllOfAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailTokenAllOfAttributes(val *EmailTokenAllOfAttributes) *NullableEmailTokenAllOfAttributes {
	return &NullableEmailTokenAllOfAttributes{value: val, isSet: true}
}

func (v NullableEmailTokenAllOfAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailTokenAllOfAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
