/*
Apodeixis backend

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SignUpRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SignUpRequest{}

// SignUpRequest struct for SignUpRequest
type SignUpRequest struct {
	Data SignUpUser `json:"data"`
}

type _SignUpRequest SignUpRequest

// NewSignUpRequest instantiates a new SignUpRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSignUpRequest(data SignUpUser) *SignUpRequest {
	this := SignUpRequest{}
	this.Data = data
	return &this
}

// NewSignUpRequestWithDefaults instantiates a new SignUpRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSignUpRequestWithDefaults() *SignUpRequest {
	this := SignUpRequest{}
	return &this
}

// GetData returns the Data field value
func (o *SignUpRequest) GetData() SignUpUser {
	if o == nil {
		var ret SignUpUser
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SignUpRequest) GetDataOk() (*SignUpUser, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *SignUpRequest) SetData(v SignUpUser) {
	o.Data = v
}

func (o SignUpRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SignUpRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *SignUpRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSignUpRequest := _SignUpRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSignUpRequest)

	if err != nil {
		return err
	}

	*o = SignUpRequest(varSignUpRequest)

	return err
}

type NullableSignUpRequest struct {
	value *SignUpRequest
	isSet bool
}

func (v NullableSignUpRequest) Get() *SignUpRequest {
	return v.value
}

func (v *NullableSignUpRequest) Set(val *SignUpRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSignUpRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSignUpRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSignUpRequest(val *SignUpRequest) *NullableSignUpRequest {
	return &NullableSignUpRequest{value: val, isSet: true}
}

func (v NullableSignUpRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSignUpRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
