/*
Apodeixis backend

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SendPasswordRecoveryEmailRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SendPasswordRecoveryEmailRequest{}

// SendPasswordRecoveryEmailRequest struct for SendPasswordRecoveryEmailRequest
type SendPasswordRecoveryEmailRequest struct {
	Data Email `json:"data"`
}

type _SendPasswordRecoveryEmailRequest SendPasswordRecoveryEmailRequest

// NewSendPasswordRecoveryEmailRequest instantiates a new SendPasswordRecoveryEmailRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendPasswordRecoveryEmailRequest(data Email) *SendPasswordRecoveryEmailRequest {
	this := SendPasswordRecoveryEmailRequest{}
	this.Data = data
	return &this
}

// NewSendPasswordRecoveryEmailRequestWithDefaults instantiates a new SendPasswordRecoveryEmailRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendPasswordRecoveryEmailRequestWithDefaults() *SendPasswordRecoveryEmailRequest {
	this := SendPasswordRecoveryEmailRequest{}
	return &this
}

// GetData returns the Data field value
func (o *SendPasswordRecoveryEmailRequest) GetData() Email {
	if o == nil {
		var ret Email
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SendPasswordRecoveryEmailRequest) GetDataOk() (*Email, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *SendPasswordRecoveryEmailRequest) SetData(v Email) {
	o.Data = v
}

func (o SendPasswordRecoveryEmailRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SendPasswordRecoveryEmailRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *SendPasswordRecoveryEmailRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSendPasswordRecoveryEmailRequest := _SendPasswordRecoveryEmailRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSendPasswordRecoveryEmailRequest)

	if err != nil {
		return err
	}

	*o = SendPasswordRecoveryEmailRequest(varSendPasswordRecoveryEmailRequest)

	return err
}

type NullableSendPasswordRecoveryEmailRequest struct {
	value *SendPasswordRecoveryEmailRequest
	isSet bool
}

func (v NullableSendPasswordRecoveryEmailRequest) Get() *SendPasswordRecoveryEmailRequest {
	return v.value
}

func (v *NullableSendPasswordRecoveryEmailRequest) Set(val *SendPasswordRecoveryEmailRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSendPasswordRecoveryEmailRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSendPasswordRecoveryEmailRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendPasswordRecoveryEmailRequest(val *SendPasswordRecoveryEmailRequest) *NullableSendPasswordRecoveryEmailRequest {
	return &NullableSendPasswordRecoveryEmailRequest{value: val, isSet: true}
}

func (v NullableSendPasswordRecoveryEmailRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendPasswordRecoveryEmailRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
