/*
Apodeixis backend

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreatePost type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatePost{}

// CreatePost struct for CreatePost
type CreatePost struct {
	Type       string                    `json:"type"`
	Attributes CreatePostAllOfAttributes `json:"attributes"`
}

type _CreatePost CreatePost

// NewCreatePost instantiates a new CreatePost object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePost(type_ string, attributes CreatePostAllOfAttributes) *CreatePost {
	this := CreatePost{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewCreatePostWithDefaults instantiates a new CreatePost object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePostWithDefaults() *CreatePost {
	this := CreatePost{}
	return &this
}

// GetType returns the Type field value
func (o *CreatePost) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreatePost) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreatePost) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *CreatePost) GetAttributes() CreatePostAllOfAttributes {
	if o == nil {
		var ret CreatePostAllOfAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *CreatePost) GetAttributesOk() (*CreatePostAllOfAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *CreatePost) SetAttributes(v CreatePostAllOfAttributes) {
	o.Attributes = v
}

func (o CreatePost) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatePost) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *CreatePost) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreatePost := _CreatePost{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreatePost)

	if err != nil {
		return err
	}

	*o = CreatePost(varCreatePost)

	return err
}

type NullableCreatePost struct {
	value *CreatePost
	isSet bool
}

func (v NullableCreatePost) Get() *CreatePost {
	return v.value
}

func (v *NullableCreatePost) Set(val *CreatePost) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePost) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePost(val *CreatePost) *NullableCreatePost {
	return &NullableCreatePost{value: val, isSet: true}
}

func (v NullableCreatePost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
