/*
Apodeixis backend

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UserAllOfRelationshipsTokens type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserAllOfRelationshipsTokens{}

// UserAllOfRelationshipsTokens struct for UserAllOfRelationshipsTokens
type UserAllOfRelationshipsTokens struct {
	Data AuthTokenKey `json:"data"`
}

type _UserAllOfRelationshipsTokens UserAllOfRelationshipsTokens

// NewUserAllOfRelationshipsTokens instantiates a new UserAllOfRelationshipsTokens object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserAllOfRelationshipsTokens(data AuthTokenKey) *UserAllOfRelationshipsTokens {
	this := UserAllOfRelationshipsTokens{}
	this.Data = data
	return &this
}

// NewUserAllOfRelationshipsTokensWithDefaults instantiates a new UserAllOfRelationshipsTokens object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserAllOfRelationshipsTokensWithDefaults() *UserAllOfRelationshipsTokens {
	this := UserAllOfRelationshipsTokens{}
	return &this
}

// GetData returns the Data field value
func (o *UserAllOfRelationshipsTokens) GetData() AuthTokenKey {
	if o == nil {
		var ret AuthTokenKey
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UserAllOfRelationshipsTokens) GetDataOk() (*AuthTokenKey, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UserAllOfRelationshipsTokens) SetData(v AuthTokenKey) {
	o.Data = v
}

func (o UserAllOfRelationshipsTokens) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserAllOfRelationshipsTokens) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UserAllOfRelationshipsTokens) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserAllOfRelationshipsTokens := _UserAllOfRelationshipsTokens{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserAllOfRelationshipsTokens)

	if err != nil {
		return err
	}

	*o = UserAllOfRelationshipsTokens(varUserAllOfRelationshipsTokens)

	return err
}

type NullableUserAllOfRelationshipsTokens struct {
	value *UserAllOfRelationshipsTokens
	isSet bool
}

func (v NullableUserAllOfRelationshipsTokens) Get() *UserAllOfRelationshipsTokens {
	return v.value
}

func (v *NullableUserAllOfRelationshipsTokens) Set(val *UserAllOfRelationshipsTokens) {
	v.value = val
	v.isSet = true
}

func (v NullableUserAllOfRelationshipsTokens) IsSet() bool {
	return v.isSet
}

func (v *NullableUserAllOfRelationshipsTokens) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserAllOfRelationshipsTokens(val *UserAllOfRelationshipsTokens) *NullableUserAllOfRelationshipsTokens {
	return &NullableUserAllOfRelationshipsTokens{value: val, isSet: true}
}

func (v NullableUserAllOfRelationshipsTokens) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserAllOfRelationshipsTokens) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
