/*
Apodeixis backend

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the OAuth2AllOfAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OAuth2AllOfAttributes{}

// OAuth2AllOfAttributes struct for OAuth2AllOfAttributes
type OAuth2AllOfAttributes struct {
	Url string `json:"url"`
}

type _OAuth2AllOfAttributes OAuth2AllOfAttributes

// NewOAuth2AllOfAttributes instantiates a new OAuth2AllOfAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOAuth2AllOfAttributes(url string) *OAuth2AllOfAttributes {
	this := OAuth2AllOfAttributes{}
	this.Url = url
	return &this
}

// NewOAuth2AllOfAttributesWithDefaults instantiates a new OAuth2AllOfAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOAuth2AllOfAttributesWithDefaults() *OAuth2AllOfAttributes {
	this := OAuth2AllOfAttributes{}
	return &this
}

// GetUrl returns the Url field value
func (o *OAuth2AllOfAttributes) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *OAuth2AllOfAttributes) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *OAuth2AllOfAttributes) SetUrl(v string) {
	o.Url = v
}

func (o OAuth2AllOfAttributes) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OAuth2AllOfAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *OAuth2AllOfAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOAuth2AllOfAttributes := _OAuth2AllOfAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOAuth2AllOfAttributes)

	if err != nil {
		return err
	}

	*o = OAuth2AllOfAttributes(varOAuth2AllOfAttributes)

	return err
}

type NullableOAuth2AllOfAttributes struct {
	value *OAuth2AllOfAttributes
	isSet bool
}

func (v NullableOAuth2AllOfAttributes) Get() *OAuth2AllOfAttributes {
	return v.value
}

func (v *NullableOAuth2AllOfAttributes) Set(val *OAuth2AllOfAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableOAuth2AllOfAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableOAuth2AllOfAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOAuth2AllOfAttributes(val *OAuth2AllOfAttributes) *NullableOAuth2AllOfAttributes {
	return &NullableOAuth2AllOfAttributes{value: val, isSet: true}
}

func (v NullableOAuth2AllOfAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOAuth2AllOfAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
