/*
Apodeixis backend

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the EditRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EditRequest{}

// EditRequest struct for EditRequest
type EditRequest struct {
	Data EditUser `json:"data"`
}

type _EditRequest EditRequest

// NewEditRequest instantiates a new EditRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEditRequest(data EditUser) *EditRequest {
	this := EditRequest{}
	this.Data = data
	return &this
}

// NewEditRequestWithDefaults instantiates a new EditRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEditRequestWithDefaults() *EditRequest {
	this := EditRequest{}
	return &this
}

// GetData returns the Data field value
func (o *EditRequest) GetData() EditUser {
	if o == nil {
		var ret EditUser
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *EditRequest) GetDataOk() (*EditUser, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *EditRequest) SetData(v EditUser) {
	o.Data = v
}

func (o EditRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EditRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *EditRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEditRequest := _EditRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEditRequest)

	if err != nil {
		return err
	}

	*o = EditRequest(varEditRequest)

	return err
}

type NullableEditRequest struct {
	value *EditRequest
	isSet bool
}

func (v NullableEditRequest) Get() *EditRequest {
	return v.value
}

func (v *NullableEditRequest) Set(val *EditRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEditRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEditRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEditRequest(val *EditRequest) *NullableEditRequest {
	return &NullableEditRequest{value: val, isSet: true}
}

func (v NullableEditRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEditRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
