/*
Apodeixis backend

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreatePostAllOfAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatePostAllOfAttributes{}

// CreatePostAllOfAttributes struct for CreatePostAllOfAttributes
type CreatePostAllOfAttributes struct {
	Title string `json:"title"`
	Body  string `json:"body"`
}

type _CreatePostAllOfAttributes CreatePostAllOfAttributes

// NewCreatePostAllOfAttributes instantiates a new CreatePostAllOfAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePostAllOfAttributes(title string, body string) *CreatePostAllOfAttributes {
	this := CreatePostAllOfAttributes{}
	this.Title = title
	this.Body = body
	return &this
}

// NewCreatePostAllOfAttributesWithDefaults instantiates a new CreatePostAllOfAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePostAllOfAttributesWithDefaults() *CreatePostAllOfAttributes {
	this := CreatePostAllOfAttributes{}
	return &this
}

// GetTitle returns the Title field value
func (o *CreatePostAllOfAttributes) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *CreatePostAllOfAttributes) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *CreatePostAllOfAttributes) SetTitle(v string) {
	o.Title = v
}

// GetBody returns the Body field value
func (o *CreatePostAllOfAttributes) GetBody() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Body
}

// GetBodyOk returns a tuple with the Body field value
// and a boolean to check if the value has been set.
func (o *CreatePostAllOfAttributes) GetBodyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Body, true
}

// SetBody sets field value
func (o *CreatePostAllOfAttributes) SetBody(v string) {
	o.Body = v
}

func (o CreatePostAllOfAttributes) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatePostAllOfAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["title"] = o.Title
	toSerialize["body"] = o.Body
	return toSerialize, nil
}

func (o *CreatePostAllOfAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"title",
		"body",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreatePostAllOfAttributes := _CreatePostAllOfAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreatePostAllOfAttributes)

	if err != nil {
		return err
	}

	*o = CreatePostAllOfAttributes(varCreatePostAllOfAttributes)

	return err
}

type NullableCreatePostAllOfAttributes struct {
	value *CreatePostAllOfAttributes
	isSet bool
}

func (v NullableCreatePostAllOfAttributes) Get() *CreatePostAllOfAttributes {
	return v.value
}

func (v *NullableCreatePostAllOfAttributes) Set(val *CreatePostAllOfAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePostAllOfAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePostAllOfAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePostAllOfAttributes(val *CreatePostAllOfAttributes) *NullableCreatePostAllOfAttributes {
	return &NullableCreatePostAllOfAttributes{value: val, isSet: true}
}

func (v NullableCreatePostAllOfAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePostAllOfAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
