/*
Apodeixis backend

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PostKey type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostKey{}

// PostKey struct for PostKey
type PostKey struct {
	Id   string `json:"id"`
	Type string `json:"type"`
}

type _PostKey PostKey

// NewPostKey instantiates a new PostKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostKey(id string, type_ string) *PostKey {
	this := PostKey{}
	this.Id = id
	this.Type = type_
	return &this
}

// NewPostKeyWithDefaults instantiates a new PostKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostKeyWithDefaults() *PostKey {
	this := PostKey{}
	return &this
}

// GetId returns the Id field value
func (o *PostKey) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PostKey) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PostKey) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *PostKey) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PostKey) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PostKey) SetType(v string) {
	o.Type = v
}

func (o PostKey) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostKey) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *PostKey) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostKey := _PostKey{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPostKey)

	if err != nil {
		return err
	}

	*o = PostKey(varPostKey)

	return err
}

type NullablePostKey struct {
	value *PostKey
	isSet bool
}

func (v NullablePostKey) Get() *PostKey {
	return v.value
}

func (v *NullablePostKey) Set(val *PostKey) {
	v.value = val
	v.isSet = true
}

func (v NullablePostKey) IsSet() bool {
	return v.isSet
}

func (v *NullablePostKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostKey(val *PostKey) *NullablePostKey {
	return &NullablePostKey{value: val, isSet: true}
}

func (v NullablePostKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
