/*
Apodeixis backend

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the RecoverPasswordCallback200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecoverPasswordCallback200Response{}

// RecoverPasswordCallback200Response struct for RecoverPasswordCallback200Response
type RecoverPasswordCallback200Response struct {
	Data User `json:"data"`
}

type _RecoverPasswordCallback200Response RecoverPasswordCallback200Response

// NewRecoverPasswordCallback200Response instantiates a new RecoverPasswordCallback200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecoverPasswordCallback200Response(data User) *RecoverPasswordCallback200Response {
	this := RecoverPasswordCallback200Response{}
	this.Data = data
	return &this
}

// NewRecoverPasswordCallback200ResponseWithDefaults instantiates a new RecoverPasswordCallback200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecoverPasswordCallback200ResponseWithDefaults() *RecoverPasswordCallback200Response {
	this := RecoverPasswordCallback200Response{}
	return &this
}

// GetData returns the Data field value
func (o *RecoverPasswordCallback200Response) GetData() User {
	if o == nil {
		var ret User
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *RecoverPasswordCallback200Response) GetDataOk() (*User, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *RecoverPasswordCallback200Response) SetData(v User) {
	o.Data = v
}

func (o RecoverPasswordCallback200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecoverPasswordCallback200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *RecoverPasswordCallback200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRecoverPasswordCallback200Response := _RecoverPasswordCallback200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRecoverPasswordCallback200Response)

	if err != nil {
		return err
	}

	*o = RecoverPasswordCallback200Response(varRecoverPasswordCallback200Response)

	return err
}

type NullableRecoverPasswordCallback200Response struct {
	value *RecoverPasswordCallback200Response
	isSet bool
}

func (v NullableRecoverPasswordCallback200Response) Get() *RecoverPasswordCallback200Response {
	return v.value
}

func (v *NullableRecoverPasswordCallback200Response) Set(val *RecoverPasswordCallback200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableRecoverPasswordCallback200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableRecoverPasswordCallback200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecoverPasswordCallback200Response(val *RecoverPasswordCallback200Response) *NullableRecoverPasswordCallback200Response {
	return &NullableRecoverPasswordCallback200Response{value: val, isSet: true}
}

func (v NullableRecoverPasswordCallback200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecoverPasswordCallback200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
