/*
Apodeixis backend

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the LoginUserAllOfAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LoginUserAllOfAttributes{}

// LoginUserAllOfAttributes struct for LoginUserAllOfAttributes
type LoginUserAllOfAttributes struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type _LoginUserAllOfAttributes LoginUserAllOfAttributes

// NewLoginUserAllOfAttributes instantiates a new LoginUserAllOfAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoginUserAllOfAttributes(email string, password string) *LoginUserAllOfAttributes {
	this := LoginUserAllOfAttributes{}
	this.Email = email
	this.Password = password
	return &this
}

// NewLoginUserAllOfAttributesWithDefaults instantiates a new LoginUserAllOfAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoginUserAllOfAttributesWithDefaults() *LoginUserAllOfAttributes {
	this := LoginUserAllOfAttributes{}
	return &this
}

// GetEmail returns the Email field value
func (o *LoginUserAllOfAttributes) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *LoginUserAllOfAttributes) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *LoginUserAllOfAttributes) SetEmail(v string) {
	o.Email = v
}

// GetPassword returns the Password field value
func (o *LoginUserAllOfAttributes) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *LoginUserAllOfAttributes) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *LoginUserAllOfAttributes) SetPassword(v string) {
	o.Password = v
}

func (o LoginUserAllOfAttributes) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LoginUserAllOfAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	toSerialize["password"] = o.Password
	return toSerialize, nil
}

func (o *LoginUserAllOfAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLoginUserAllOfAttributes := _LoginUserAllOfAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLoginUserAllOfAttributes)

	if err != nil {
		return err
	}

	*o = LoginUserAllOfAttributes(varLoginUserAllOfAttributes)

	return err
}

type NullableLoginUserAllOfAttributes struct {
	value *LoginUserAllOfAttributes
	isSet bool
}

func (v NullableLoginUserAllOfAttributes) Get() *LoginUserAllOfAttributes {
	return v.value
}

func (v *NullableLoginUserAllOfAttributes) Set(val *LoginUserAllOfAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableLoginUserAllOfAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableLoginUserAllOfAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoginUserAllOfAttributes(val *LoginUserAllOfAttributes) *NullableLoginUserAllOfAttributes {
	return &NullableLoginUserAllOfAttributes{value: val, isSet: true}
}

func (v NullableLoginUserAllOfAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoginUserAllOfAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
