/*
Apodeixis backend

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"fmt"
)

// CreatePost201ResponseIncludedInner struct for CreatePost201ResponseIncludedInner
type CreatePost201ResponseIncludedInner struct {
	User *User
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *CreatePost201ResponseIncludedInner) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into User
	err = json.Unmarshal(data, &dst.User)
	if err == nil {
		jsonUser, _ := json.Marshal(dst.User)
		if string(jsonUser) == "{}" { // empty struct
			dst.User = nil
		} else {
			return nil // data stored in dst.User, return on the first match
		}
	} else {
		dst.User = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(CreatePost201ResponseIncludedInner)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *CreatePost201ResponseIncludedInner) MarshalJSON() ([]byte, error) {
	if src.User != nil {
		return json.Marshal(&src.User)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableCreatePost201ResponseIncludedInner struct {
	value *CreatePost201ResponseIncludedInner
	isSet bool
}

func (v NullableCreatePost201ResponseIncludedInner) Get() *CreatePost201ResponseIncludedInner {
	return v.value
}

func (v *NullableCreatePost201ResponseIncludedInner) Set(val *CreatePost201ResponseIncludedInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePost201ResponseIncludedInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePost201ResponseIncludedInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePost201ResponseIncludedInner(val *CreatePost201ResponseIncludedInner) *NullableCreatePost201ResponseIncludedInner {
	return &NullableCreatePost201ResponseIncludedInner{value: val, isSet: true}
}

func (v NullableCreatePost201ResponseIncludedInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePost201ResponseIncludedInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
