/*
Apodeixis backend

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the RecoverPasswordCallbackRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecoverPasswordCallbackRequest{}

// RecoverPasswordCallbackRequest struct for RecoverPasswordCallbackRequest
type RecoverPasswordCallbackRequest struct {
	Data RecoverPassword `json:"data"`
}

type _RecoverPasswordCallbackRequest RecoverPasswordCallbackRequest

// NewRecoverPasswordCallbackRequest instantiates a new RecoverPasswordCallbackRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecoverPasswordCallbackRequest(data RecoverPassword) *RecoverPasswordCallbackRequest {
	this := RecoverPasswordCallbackRequest{}
	this.Data = data
	return &this
}

// NewRecoverPasswordCallbackRequestWithDefaults instantiates a new RecoverPasswordCallbackRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecoverPasswordCallbackRequestWithDefaults() *RecoverPasswordCallbackRequest {
	this := RecoverPasswordCallbackRequest{}
	return &this
}

// GetData returns the Data field value
func (o *RecoverPasswordCallbackRequest) GetData() RecoverPassword {
	if o == nil {
		var ret RecoverPassword
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *RecoverPasswordCallbackRequest) GetDataOk() (*RecoverPassword, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *RecoverPasswordCallbackRequest) SetData(v RecoverPassword) {
	o.Data = v
}

func (o RecoverPasswordCallbackRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecoverPasswordCallbackRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *RecoverPasswordCallbackRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRecoverPasswordCallbackRequest := _RecoverPasswordCallbackRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRecoverPasswordCallbackRequest)

	if err != nil {
		return err
	}

	*o = RecoverPasswordCallbackRequest(varRecoverPasswordCallbackRequest)

	return err
}

type NullableRecoverPasswordCallbackRequest struct {
	value *RecoverPasswordCallbackRequest
	isSet bool
}

func (v NullableRecoverPasswordCallbackRequest) Get() *RecoverPasswordCallbackRequest {
	return v.value
}

func (v *NullableRecoverPasswordCallbackRequest) Set(val *RecoverPasswordCallbackRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRecoverPasswordCallbackRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRecoverPasswordCallbackRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecoverPasswordCallbackRequest(val *RecoverPasswordCallbackRequest) *NullableRecoverPasswordCallbackRequest {
	return &NullableRecoverPasswordCallbackRequest{value: val, isSet: true}
}

func (v NullableRecoverPasswordCallbackRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecoverPasswordCallbackRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
