/*
Apodeixis backend

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the RecoverPassword type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecoverPassword{}

// RecoverPassword struct for RecoverPassword
type RecoverPassword struct {
	Type       string                         `json:"type"`
	Attributes RecoverPasswordAllOfAttributes `json:"attributes"`
}

type _RecoverPassword RecoverPassword

// NewRecoverPassword instantiates a new RecoverPassword object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecoverPassword(type_ string, attributes RecoverPasswordAllOfAttributes) *RecoverPassword {
	this := RecoverPassword{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewRecoverPasswordWithDefaults instantiates a new RecoverPassword object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecoverPasswordWithDefaults() *RecoverPassword {
	this := RecoverPassword{}
	return &this
}

// GetType returns the Type field value
func (o *RecoverPassword) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *RecoverPassword) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *RecoverPassword) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *RecoverPassword) GetAttributes() RecoverPasswordAllOfAttributes {
	if o == nil {
		var ret RecoverPasswordAllOfAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *RecoverPassword) GetAttributesOk() (*RecoverPasswordAllOfAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *RecoverPassword) SetAttributes(v RecoverPasswordAllOfAttributes) {
	o.Attributes = v
}

func (o RecoverPassword) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecoverPassword) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *RecoverPassword) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRecoverPassword := _RecoverPassword{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRecoverPassword)

	if err != nil {
		return err
	}

	*o = RecoverPassword(varRecoverPassword)

	return err
}

type NullableRecoverPassword struct {
	value *RecoverPassword
	isSet bool
}

func (v NullableRecoverPassword) Get() *RecoverPassword {
	return v.value
}

func (v *NullableRecoverPassword) Set(val *RecoverPassword) {
	v.value = val
	v.isSet = true
}

func (v NullableRecoverPassword) IsSet() bool {
	return v.isSet
}

func (v *NullableRecoverPassword) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecoverPassword(val *RecoverPassword) *NullableRecoverPassword {
	return &NullableRecoverPassword{value: val, isSet: true}
}

func (v NullableRecoverPassword) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecoverPassword) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
