/*
Apodeixis backend

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PostAllOfRelationships type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostAllOfRelationships{}

// PostAllOfRelationships struct for PostAllOfRelationships
type PostAllOfRelationships struct {
	Author PostAllOfRelationshipsAuthor `json:"author"`
}

type _PostAllOfRelationships PostAllOfRelationships

// NewPostAllOfRelationships instantiates a new PostAllOfRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostAllOfRelationships(author PostAllOfRelationshipsAuthor) *PostAllOfRelationships {
	this := PostAllOfRelationships{}
	this.Author = author
	return &this
}

// NewPostAllOfRelationshipsWithDefaults instantiates a new PostAllOfRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostAllOfRelationshipsWithDefaults() *PostAllOfRelationships {
	this := PostAllOfRelationships{}
	return &this
}

// GetAuthor returns the Author field value
func (o *PostAllOfRelationships) GetAuthor() PostAllOfRelationshipsAuthor {
	if o == nil {
		var ret PostAllOfRelationshipsAuthor
		return ret
	}

	return o.Author
}

// GetAuthorOk returns a tuple with the Author field value
// and a boolean to check if the value has been set.
func (o *PostAllOfRelationships) GetAuthorOk() (*PostAllOfRelationshipsAuthor, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Author, true
}

// SetAuthor sets field value
func (o *PostAllOfRelationships) SetAuthor(v PostAllOfRelationshipsAuthor) {
	o.Author = v
}

func (o PostAllOfRelationships) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostAllOfRelationships) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["author"] = o.Author
	return toSerialize, nil
}

func (o *PostAllOfRelationships) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"author",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostAllOfRelationships := _PostAllOfRelationships{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPostAllOfRelationships)

	if err != nil {
		return err
	}

	*o = PostAllOfRelationships(varPostAllOfRelationships)

	return err
}

type NullablePostAllOfRelationships struct {
	value *PostAllOfRelationships
	isSet bool
}

func (v NullablePostAllOfRelationships) Get() *PostAllOfRelationships {
	return v.value
}

func (v *NullablePostAllOfRelationships) Set(val *PostAllOfRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullablePostAllOfRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullablePostAllOfRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostAllOfRelationships(val *PostAllOfRelationships) *NullablePostAllOfRelationships {
	return &NullablePostAllOfRelationships{value: val, isSet: true}
}

func (v NullablePostAllOfRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostAllOfRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
