permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  docs:
    runs-on: ubuntu-latest
    name: Docs
    steps:
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install npm dependencies and build release docs
        run: |
          cd docs
          npm install
          npm run release-build

      - uses: actions/artifact@v4
        with:
          path: './docs/public/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4