name: Test
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
      - 'develop'

jobs:
  test-nocache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19.x
          cache: false
      - run: go test ./...

  test-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19.x
      - run: go test ./...